### ISSUE TITLE
CHttpRequest::getUserHostAddress() is not static

### ISSUE THREAD

**Issue by ErikMinekus** [dlage/yii-geoip#1]
When PHP is in strict mode, [CGeoIP.php#L90](https://github.com/dlage/yii-geoip/blob/master/CGeoIP.php#L90) throws an error. It should be

``` php
$ip = Yii::app()->getRequest()->getUserHostAddress();
```

**Comment by dlage** [comment]
Thank you. Fixed in: https://github.com/dlage/yii-geoip/commit/591383f287b208eaafc4792098dc310e04402b1b

**Comment by mrccao** [comment]
CHttpRequest::getUserHostAddress()  Suitable for linux
Yii::app()->getRequest()->getUserHostAddress() Suitable for all
